# Site settings
title: Just fooling around
description: >-
  Filipe's blog and recipe collection. Recipes are written in Cooklang.
url: "https://desousa.com.pt"

# Build settings
theme: minima
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Europe/London

header_pages:
  - about.md
  - recipes.md

minima:
  date_format: "%-d %B %Y"

plugins:
  - jekyll-cooklang-converter
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  recipes:
    output: true
    permalink: /recipes/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe

# Files that shouldn't end up on the site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .github
